### ISSUE TITLE
1.17.x as minecraft dependency

### ISSUE THREAD

**Issue by n0k0m3** [TheMegax/fabric-elytra-autopilot#1]
https://github.com/TheMegax/fabric-elytra-autopilot/blob/1.17/src/main/resources/fabric.mod.json

There're no major changes from 1.17 to 1.17.x so I'd assume that this would allow the mods to work with all major version of 1.17

**Comment by TheMegax** [comment]
Fair point, I'll update it to 1.17.x. There shouldn't be any problem with any of the minor versions of 1.17.
