### ISSUE TITLE
Can't use /flyto 

### ISSUE THREAD

**Issue by BlackDragon126** [TheMegax/fabric-elytra-autopilot#12]
After giving cords error pop up in chat.

Cannot read field "minHeight" because "net.elytraautopilot.ClientCommands.config" is null 

in game output:
![1](https://user-images.githubusercontent.com/84410523/147458752-7457d79b-390f-4015-bc49-60d454aacd53.png)
![2](https://user-images.githubusercontent.com/84410523/147458754-7a8841e7-163e-46c6-b7f2-0cce7911b582.png)

**Comment by TheMegax** [comment]
Thank you! Fixed in the github commit
