### ISSUE TITLE
Gets confused in the End

### ISSUE THREAD

**Issue by Madis0** [TheMegax/fabric-elytra-autopilot#20]
Reproduce:

1. Create a survival world, go to the End
2. /takeoff
3. /flyto x z

Expected:
/flyto to work as it does in the Overworld

Actual:
Height from ground changes to "???" (presumably due to void); "You're too low to activate auto-flight!" and it doesn't seem to land safely either.

Minecraft 1.18.1, Elytra AutoPilot 1.3.0, Fabric API 0.46.2

**Comment by TheMegax** [comment]
Thanks! Fixed it in the new commit ;]
