### ISSUE TITLE
More separate and merged keybinds

### ISSUE THREAD

**Issue by Madis0** [TheMegax/fabric-elytra-autopilot#21]
More separate keybinds would be nice:

- Takeoff
- Auto-flight
- Flyto (where the crosshair is aiming)
- Land

Some settings to merge keybinds would be useful as well:

- Auto-flight and settings (like now)
- Takeoff and autoflight
- Takeoff and flyto
- Auto-flight and land

**Comment by TheMegax** [comment]
Not a bad idea! I'll take it into consideration, thanks

**Comment by TheMegax** [comment]
Implemented in 2.0.0
At least partially. The more important ones like takeoff and land are now available :]
