### ISSUE TITLE
When autoflight cannot be done, glide instead

### ISSUE THREAD

**Issue by Madis0** [TheMegax/fabric-elytra-autopilot#23]
When the height is too low to autoflight, fix the player's angle to glide instead, like [FlightHelper](https://www.curseforge.com/minecraft/mc-mods/flighthelper). Should be configurable.

**Comment by TheMegax** [comment]
Heya! Yeah I think I made something like that at one point but didn't think it felt right. I can bring that back if it's needed ;]

**Comment by TheMegax** [comment]
Implemented in 2.0.0 ;]
