### ISSUE TITLE
support named destinations with /flyto

### ISSUE THREAD

**Issue by NovaStorm93** [TheMegax/fabric-elytra-autopilot#33]
With frequent trips, instead of having to grab the coordinates every time, you can bind a set of coordinates to a name

/location [Name] [X] [Z]

then, while using /flyto, you can input a name

/flyto [Name]

**Comment by NiciTheNici** [comment]
+1

**Comment by TheMegax** [comment]
Sure, I can get that to work :]

**Comment by TheMegax** [comment]
Implemented in 2.0.0 ;]

**Comment by matthewsong18** [comment]
Can you add a feature where it will show all your saved locations if you press the tab button after /flyto? It's like this for other Minecraft commands.
