### ISSUE TITLE
User control lockout on unsuccessful activation beneath autopilot minimum height

### ISSUE THREAD

**Issue by sloraris** [TheMegax/fabric-elytra-autopilot#36]
Attempting to activate autopilot beneath the minimum altitude (default 180 blocks) is resulting in closing the wings, pointing the camera towards the ground, and preventing the user from moving the mouse up and down. Pressing the escape key or the toggle for autopilot/gui results in the game menu or autopilot mod configuration pane. All other movement controls are allowed but result in a lot of screen bugging. (I was thankfully above water on every occasion this has occurred so far)

I'm not super familiar with Java, but I believe the issue is an if statement with no else case in the ElytraAutoPilot.java around line 130-159. I could also be very wrong, and probably am unfortunately lol, but it's cool looking under the hood anyways. If you would like any feedback or testing let me know! Happy to help.

**Comment by Arden144** [comment]
can confirm, happens on my paper 1.19.2 server

**Comment by 0subzero** [comment]
Yes, quite not funny situation. Have to disable mod until its fixed.

**Comment by EMG999** [comment]
Yep has resulted in my death on a few severs. I have to /kill myself before it stops. It would be nice if you could configure a hotkey that disables/pauses all elytra autopilot stuff incase that happens or you want to take control.

**Comment by 0subzero** [comment]
Kinda workaround would be change elytraautopilot.conf
minHeight=0

So no any glitches for now but you should be careful.

**Comment by TheMegax** [comment]
Your initial intuition was correct, there was a problem for how I implemented the glide code, with it being at odds with another piece of code. It should work fully as intended, but if it happens again there's now a failsave with the pause button so it unlocks user control at will.

**Comment by MachineRat8** [comment]
Will this fix be backported to 1.19.2, or is development for that version over?
