### ISSUE TITLE
Powered flight

### ISSUE THREAD

**Issue by TheMegax** [TheMegax/fabric-elytra-autopilot#4]
Use fireworks while auto-flying. Simple and easy, if a bit expensive in the long run.

**Comment by ghost** [comment]
Super-Duper Great Idea. I hope you will update that feature to your mods.

**Comment by Loh-key** [comment]
I second this :) have a plenty efficient gp farm, rockets aren't the issue.  It's being able to afk while flying long distances :) be nice if they were slightly shorter afks

**Comment by TheMegax** [comment]
Alright, this has been kicked down the road for way too long, I'll better do this before I forget

**Comment by TheMegax** [comment]
(Finally) Implemented in 2.0.0 ;]
