### ISSUE TITLE
Unknown Bug Forces Cursor Downwards

### ISSUE THREAD

**Issue by matthewsong18** [TheMegax/fabric-elytra-autopilot#40]
I apologize for being unable to be more detailed about the issue. I am new to using this mod, but I've encountered a problem where my cursor is forced downwards and locked there, which sends me hurtling toward the ground and dying. Unfortunately, I have been unable to understand why this issue occurs.

I believe, however, that it originates from the takeoff phase; both times, I think I wanted to cancel but was locked downwards.

I will update this if I discover how to replicate this issue.

Possible Fix: Canceling whatever action is currently queued or in progress if the user moves their cursor. Changing the user back to being free when they move will prevent unknown bugs from locking them in a direction that would cause certain death. This could be an option that could be enabled/disabled.

Another option would be a Force Cancel button that turns off the mod, freeing the user of the control.

**Comment by matthewsong18** [comment]
I have discovered how to replicate this issue.

After you press Takeoff, before you reach the "Needed Height," if you cancel and look downwards, the cursor shoots straight to the ground, locking you there.

It is impossible to cancel the lock without closing the client; sometimes, the state is still in motion after entering the world.

Suppose you press takeoff/abort while locked downwards. It will start jumping while trying to fly you into the ground. Pressing abort will stop the jumping but won't let you move the cursor.

Is the mod tracking the cursor, even while it shouldn't be on? A force-cancel button is needed.

**Comment by imadraude** [comment]
same issue, hoping for fix
