### ISSUE TITLE
/flyto throws null pointer exception

### ISSUE THREAD

**Issue by TheMegax** [TheMegax/fabric-elytra-autopilot#7]
Just as the title says. Leaving this here so I don't forget to fix it.

**Comment by TheMegax** [comment]
That was embarrassingly easy to fix

**Comment by MachineRat8** [comment]
For me, running /flyto still throws a null pointer exception. I am using no mods and I am running 1.17.1 from the latest commit.
[flyto-bug-report.txt](https://github.com/TheMegax/fabric-elytra-autopilot/files/7654041/flyto-bug-report.txt)
