### ISSUE TITLE
Add elytrafly mode

### ISSUE THREAD

**Issue by maxsupermanhd** [TheMegax/fabric-elytra-autopilot#8]
So basically if you are playing on server where modifying clients is allowed (in heavy way) (aka hacks) why not just use elytrafly, not only it is faster but it can also be safer and have more variability to path selection since you don't need to worry about getting speed.

**Comment by TheMegax** [comment]
The feature would require modified packets, that being outside the scope of the project. This mod could theorically be mixed with a hacked client, but by itself only uses legal movements
